FROM php:7.2-fpm

COPY sources.list /etc/apt/sources.list
RUN apt update \
    && apt install curl libcurl4-gnutls-dev git zlib1g-dev  -y \
    && docker-php-ext-install zip \
        # install php extension
    && mkdir /tmp/skywalking && cd /tmp/skywalking \
    && curl -L https://github.com/SkyAPM/SkyAPM-php-sdk/archive/3.0.0.tar.gz -o SkyAPM-php-sdk-3.0.0.tar.gz \
    && tar xzf SkyAPM-php-sdk-3.0.0.tar.gz \
        && cd SkyAPM-php-sdk-3.0.0 \
        && phpize && ./configure && make && make install \
        && curl -L https://github.com/SkyAPM/SkyAPM-php-sdk/releases/download/3.0.0/sky_php_agent_linux_x64 -o /usr/bin/sky_php_agent \
    && chmod +x /usr/bin/sky_php_agent \
    && apt clean && rm -rf /tmp/skywalking

RUN curl -Ss https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer

COPY skywalking.ini /usr/local/etc/php/conf.d/skywalking.ini
RUN sed -i "s/127.0.0.1:11800/$SKYWALKING_ADDR/g" /usr/local/etc/php/conf.d/skywalking.ini

WORKDIR /var/www/html/project

RUN cd ../ && composer config -g repo.packagist composer https://packagist.laravel-china.org \
    && composer create-project laravel/laravel project \
    && cd project && php artisan key:generate

CMD sky_php_agent $SW_COLLECTOR_ADDRESS & php artisan serve --host 0.0.0.0 --port 80
